### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by Mev31** [kovacevic-marko/Movie-Rental-System#1]
Hey, how do you run your code for the database?

**Comment by christianago** [comment]
It is a remote database

**Comment by Mev31** [comment]
Yea, so im unable to access your database.

**Comment by kovacevic-marko** [comment]
Hi guys, you must host MySQL database to run project. I have just uploaded database https://github.com/kovacevic-marko/Movie-Rental-System/blob/master/Database/kovacevi_videoklub.sql

Keep learning programming. Regards :)
